module.exports ={
 absoluteSumoDir: '/home/francesco/Documenti/ReSuMo/.sumo',
 sumoDir: '.sumo',
baselineDir: '.sumo/baseline',
 killedDir: '.sumo/killed',
 liveDir: '.sumo/live',
 mutantsDir: '.sumo/mutants',
 contractsGlob: '/**/*.sol',
 targetDir: '/home/francesco/Documenti/Progetti/RegressionSafeContract/safe-contracts',
 contractsDir: '/home/francesco/Documenti/Progetti/RegressionSafeContract/safe-contracts/contracts',
 testDir: '/home/francesco/Documenti/Progetti/RegressionSafeContract/safe-contracts/test',
 compiledDir: '/home/francesco/Documenti/Progetti/RegressionSafeContract/safe-contracts/client/src/contracts',
 ignore: ['/home/francesco/Documenti/Progetti/RegressionSafeContract/safe-contracts/contracts/GnosisSafeL2.sol','/home/francesco/Documenti/Progetti/RegressionSafeContract/safe-contracts/contracts/external/GnosisSafeMath.sol','/home/francesco/Documenti/Progetti/RegressionSafeContract/safe-contracts/contracts/interfaces/ERC1155TokenReceiver.sol','/home/francesco/Documenti/Progetti/RegressionSafeContract/safe-contracts/contracts/interfaces/ERC721TokenReceiver.sol','/home/francesco/Documenti/Progetti/RegressionSafeContract/safe-contracts/contracts/interfaces/ERC777TokensRecipient.sol','/home/francesco/Documenti/Progetti/RegressionSafeContract/safe-contracts/contracts/interfaces/IERC165.sol','/home/francesco/Documenti/Progetti/RegressionSafeContract/safe-contracts/contracts/interfaces/ISignatureValidator.sol','/home/francesco/Documenti/Progetti/RegressionSafeContract/safe-contracts/contracts/interfaces/ViewStorageAccessible.sol','/home/francesco/Documenti/Progetti/RegressionSafeContract/safe-contracts/contracts/libraries/CreateCall.sol','/home/francesco/Documenti/Progetti/RegressionSafeContract/safe-contracts/contracts/libraries/Migrate_1_3_0_to_1_2_0.sol','/home/francesco/Documenti/Progetti/RegressionSafeContract/safe-contracts/contracts/libraries/MultiSend.sol','/home/francesco/Documenti/Progetti/RegressionSafeContract/safe-contracts/contracts/libraries/MultiSendCallOnly.sol','/home/francesco/Documenti/Progetti/RegressionSafeContract/safe-contracts/contracts/test/ERC1155Token.sol','/home/francesco/Documenti/Progetti/RegressionSafeContract/safe-contracts/contracts/test/ERC20Token.sol','/home/francesco/Documenti/Progetti/RegressionSafeContract/safe-contracts/contracts/test/TestHandler.sol','/home/francesco/Documenti/Progetti/RegressionSafeContract/safe-contracts/contracts/test/Token.sol'],
 testConfigGlob: ['/truffle-config.js', '/hardhat.config.js', '/hardhat.config.ts'],
 packageManagerGlob: ['/package-lock.json', '/yarn.lock'],
 ganache: true,
 optimized: true,
 tce: true,
 customTestScript: true,
 regressionTestingActived: true,
 testingTimeOutInSec: 300,
 skipTests: [''],
  testsGlob: '/**/*.{js,sol,ts}',
resumeDir: '',
}
