module.exports ={
 sumoDir: '.sumo',
 resumeDir: '.resume',
 baselineDir: '.sumo/baseline',
 killedDir: '.sumo/killed',
 liveDir: '.sumo/live',
 mutantsDir: '.sumo/mutants',
 contractsGlob: '/**/*.sol',
 packageManagerGlob: ['/package-lock.json', '/yarn.lock'],

 testConfigGlob: ['/truffle-config.js', '/hardhat.config.js', '/hardhat.config.ts'],
 testsGlob: '/**/*.{js,sol,ts}',
 absoluteSumoDir: '',
 targetDir: '',
 contractsDir: '',
 testDir: '',
 compiledDir: '',
 ignore: [
   ],
 skipTests: [''],
 ganache: true,
 optimized: true,
 tce: true,
 customTestScript: true,
 regressionTestingActived: false,
 testingTimeOutInSec: 300,
}
